### PR TITLE
Added NuGet package information.

### PR DESCRIPTION
**Pull request by william-gross**
Added NuGet info in response to issue #4.

### CODE REVIEW

**Comment by william-gross** [comment]
@samuelneff I hope this PR looks good to you. I just wanted to mention that the reason I changed "Debug" to "Release" in the .csproj was to ensure that the NuGet package gets built using the Release output instead of the Debug output, even if whoever creates the package forgets to specify this on the command line. Please let me know if you have any other questions about what I did.

**Comment by samuelneff** [comment]
Thank you. I'm very happy with this pull request and will try to remember to update the nuget package and version number as I merge other updates. If I forget and you see other things merged, feel free to create additional merge requests related to the nuget package.

Sam

**Comment by samuelneff** [comment]
@william-gross I just merged some pull requests and made a few additions. I updated the version number and refactored some things. Before I publish the update, would you mind reviewing to let me know if I should make any changes to the `.nuspec` file, particularly related to the refactorings.

Thanks,

Sam

**Comment by william-gross** [comment]
@samuelneff I just submitted PR #10 to bring the nuspec file in line with the new project name. Also, since you made breaking changes to the project, we needed to bump the major version number to maintain compliance with Semantic Versioning. Everything else you did looks good to me!

I also just published the current version of the library to NuGet: https://www.nuget.org/packages/MediaTypeMap/

In the future, I will continue publishing to NuGet whenever the master branch moves forward. And I'll make sure to change the version number if you ever forget.

**Comment by samuelneff** [comment]
@william-gross I updated the mime type map today to include `GetExtension` and a major internal refactoring to do it efficiently. Can you pull latest into NuGet? I already incremented the version number so I don't think you need to make any changes to the code (if you do, let me know and I'll try to remember everything required next time).

Thanks,

Sam

**Comment by william-gross** [comment]
@samuelneff Done! 2.1.0 is published. Thanks for incrementing the version--that's all that was necessary. Here's what I do when publishing:

1. Open the solution and do a Release build.
2. Run `nuget pack` from the `src/MimeTypes` directory. This implicitly uses the .nuspec file.
3. Upload the resulting .nupkg file to the NuGet Gallery.

Thank you for your continuing work on this project!

**Pull request merged**
