### PR TITLE
Adding support for HEIC

### PR DESCRIPTION
**Pull request by paal123**
Currently missing support for heic -format

### CODE REVIEW

**Comment by samuelneff** [comment]
Thank you for submitting this PR. I've checked and confirmed the addition is correct.

Note that it doesn't needed to be added to both sections of the dictionary. Typically new types are only added to the extension to mime type mapping. The reverse mapping is added automatically. A manual reverse mapping is only needed when there is anbiguity--a single mime type could map to multiple extensions.

In looking this one up, I found there are a bunch of other related extensions and mime types it would make sense to include.

If you have time to update the PR and include all of these within the extension to mime-type map only, that would be great.

If not, I'll try to find some time myself to do these updates. 

Thank you again for pointing out this missing mapping.

https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format

**Comment by paal123** [comment]
I will remove the reverse mapping again, and add the rest of the high efficiency image file formats.

**Comment by paal123** [comment]
List is now updated @samuelneff

**Comment by samuelneff** [comment]
Thanks for all the additions!!

**Pull request merged**
