### PR TITLE
Added some const strings, fixed some typos and add default value for GetExtension method

### PR DESCRIPTION
**Pull request by StefH**
- Fixed some typos
- Add some const strings
- Used nameof in throwing exceptions
- Added a default value for method GetExtension

### CODE REVIEW

**Comment by samuelneff** [comment]
@StefH Thanks for the great additions and corrections. Everything in the map file is perfect.

I can't accept the project file changes though. Some people are dependent on that specific targeting. If you can undo just that change for the PR I'll be grateful to merge the rest of the changes.

**Comment by StefH** [comment]
Hello @samuelneff,
I can revert the TargetFrameworks change, however I would like to explain why I did this: all I did was lower the dependencies, which is good because more projects / people can use it.

- net45 --> I lowered this to net40
- netcoreapp2.0 --> I removed this because netstandard2.0 is enough, there is no need to support netcoreapp2.x or 3.x
- netstandard2.0 --> I kept this one, and also lowered to 1.1 and included 2.1

I you still would like to keep the TargetFrameworks as-is, no problem, I'll revert this in the PR.

**Comment by samuelneff** [comment]
Thanks for explaining. I haven't programmed in .NET myself in years so I don't know enough to discuss the impact of the project change. I'd prefer if you left the project as is simply to maintain status-quo.

I appreciate your understanding.

Sam

**Comment by StefH** [comment]
OK. I've reverted the changes on TargetFrameworks. Maybe I'll create a new issue on this and let other users comment on this.

When do you plan to release a new NuGet ?

**Comment by samuelneff** [comment]
@StefH Thanks for the updates. I don't control the NuGet packages. A few other people have published them but it's not something I've been involved with.

**Pull request merged**
