### PR TITLE
GetExtension function added

### PR DESCRIPTION
**Pull request by kallsbo**
Function returns the file extension from a given mime type string.

### CODE REVIEW

**Comment by samuelneff** [comment]
Thanks for offering an improvement, but I won't merge this change. To support mapping both ways, once the dictionary is loaded, loop through the dictionary once and load each entry into the dictionary again swapping key and value (and recognizing that values may be duplicates, so don't error out).

With that change, then get extension can be implemented as an efficient dictionary lookup.

As implemented in this pull request, the code will loop through the dictionary and search for the match every time it's needed. It's not efficient.

Thanks,

Sam

**Comment by kallsbo** [comment]
Totally agree with you it's not really efficient. Did this quick implementation to get extensions after file downloads fail due to errors in the file name. Since I execute the code after an exception is thrown I get more overhead in the catch then from this.

An implementation with the a reversed dictionary will give some interesting results (even though my code gives the same). For several of the mime types we have more then one file extension so if we build a new dictionary from the top down jpeg images for example will return .jpe. That works just fine but isn't the most common used type for image/jpeg.

My point being is that this works so much nicer extension -> mime type then the other way around.

However thanks for a nice class that saved me a lot of time!

**Comment by samuelneff** [comment]
@kallsbo The order of a dictionary is not guaranteed, so the behavior of looping through each time to find the matching extension vs building a new dictionary with the first matching extension will be the same, which is indeterminate.

To handle the situation where the reverse mapping could result in incorrect mappings due to duplicate, we can pre-load reverse mappings into the dictionary in the first place.

Best regards,

Sam

**Comment by samuelneff** [comment]
I committed a change that includes `GetExtension` that supports both deterministic mapping of mime type to extension and an efficient lookup.

**Pull request closed without merging**
