### PR TITLE
GetExtension() method and sorting of image/jpeg

### PR DESCRIPTION
**Pull request by alexandervantrijffel**
I added a GetExtension() method to retrieve the file extension of a given mime type. I also changed the sorting of image/jpeg so that it will return the most common .jpg extension as the result for the image/jpeg mime type.

### CODE REVIEW

**Comment by samuelneff** [comment]
Thanks for submitting the pull request.

I'm not going to merge it as is because there are two issues as I see it.

First you re-ordered the `jpg` mime types specifically to ensure that a specific one is returned by the reverse mapping. The problem with this is that the sort order of a dictionary is non-deterministic. It may be doing what you want consistently on your machine, but it could change randomly in the future as we add or remove mappings or as .NET changes.

Second, you're looping through the dictionary to find the reverse mapping, which is an O(N) operation. If we want to do a lookup then we should use another dictionary. Alternatively since the dictionary is string/string, we can store the reverse mappings in the same dictionary even. We wouldn't want to repeat the assignments--instead we can populate the reverse lookup by iterating through the forward lookup the first time we need.

Intersting that we can use the solution to the second problem to solve the first. If instead of initializing the dictionary using standard collection initializers the way we do, we can initialize the dictionary with a static method that takes an array of key/value pairs and uses them to populate the dictionary. That way we can deterministically control the order that items are added to the dictionary. We make sure the primary reverse mapping is first and then only add reverse mappings to the dictionary if there is not already a one for the same mime type.

If I can find time I'll look into applying this change myself as it is a good change. If you have time to do it, then I'll appreciate a new pull request with these changes.

Thanks!

Sam

**Comment by alexandervantrijffel** [comment]
Hi, I'll stick to my fork then. Thanks.

**Comment by samuelneff** [comment]
I committed a change that includes GetExtension that supports both deterministic mapping of mime type to extension and an efficient lookup.

**Comment by alexandervantrijffel** [comment]
Nice work!

**Pull request closed without merging**
