### PR TITLE
Update MimeTypeMap.cs

### PR DESCRIPTION
**Pull request by Thetechnicbrick**
also added .scr

### CODE REVIEW

**Comment by samuelneff** [comment]
Why are you associating `.scr` to `text/plain/`? In what context are you referring to an `.scr` file as text? I've only ever seen them as executables (screen saver), and most often in reference to trojans or viruses.

**Comment by Thetechnicbrick** [comment]
It's because the .scr is often a script file, which has plain text scrips, which is why it can sometimes be a virus.

**Comment by samuelneff** [comment]
Thanks for explaining. Can you provide some documentation or anything to back up referring to scr as a text file? I looked and couldn't find anything. Your reasoning is sound, but it's not universal. I'm not comfortable merging without more info or comments. 

If you want to submit a pull request to merge in custom mappings, I'll be happy to merge that.

**Comment by Thetechnicbrick** [comment]
http://filext.com/file-extension/SCR read the top part of that

**Comment by samuelneff** [comment]
Thanks for the link. After reading that I compared the usage and you're right, the screensaver association was much more prevalent a decade ago, but recently scr has mostly been associated with scripts.

https://www.google.com/trends/explore#q=scr%20script%2C%20scr%20%22screen%20saver%22%2C%20scr%20screensaver&cmpt=q&tz=Etc%2FGMT%2B4

I'll merge the request.

**Pull request merged**
